#ifndef DEFLATECOMPRESSIONALGORITHM_GLOBAL_H
#define DEFLATECOMPRESSIONALGORITHM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DEFLATECOMPRESSIONALGORITHM_LIBRARY)
#  define DEFLATECOMPRESSIONALGORITHMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DEFLATECOMPRESSIONALGORITHMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DEFLATECOMPRESSIONALGORITHM_GLOBAL_H
