QT.QtLzo.VERSION = 5.5.0
QT.QtLzo.MAJOR_VERSION = 5
QT.QtLzo.MINOR_VERSION = 5
QT.QtLzo.PATCH_VERSION = 0
QT.QtLzo.name = QtLzo
QT.QtLzo.module = Qt5Lzo
QT.QtLzo.libs = $$QT_MODULE_LIB_BASE
QT.QtLzo.includes = $$QT_MODULE_INCLUDE_BASE $$QT_MODULE_INCLUDE_BASE/QtLzo
QT.QtLzo.frameworks =
QT.QtLzo.bins = $$QT_MODULE_BIN_BASE
QT.QtLzo.libexecs = $$QT_MODULE_LIBEXEC_BASE
QT.QtLzo.plugins = $$QT_MODULE_PLUGIN_BASE
QT.QtLzo.imports = $$QT_MODULE_IMPORT_BASE
QT.QtLzo.qml = $$QT_MODULE_QML_BASE
QT.QtLzo.depends = core script
QT.QtLzo.module_config = v2
QT.QtLzo.DEFINES = QT_QTLZO_LIB
QT_MODULES += QtLzo
