#ifndef LZOCOMPRESSIONALGORITHM_GLOBAL_H
#define LZOCOMPRESSIONALGORITHM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LZOCOMPRESSIONALGORITHM_LIBRARY)
#  define LZOCOMPRESSIONALGORITHMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LZOCOMPRESSIONALGORITHMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LZOCOMPRESSIONALGORITHM_GLOBAL_H
